# Apply to all files without commiting:
#   pre-commit run --all-files
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=110]

  - repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile=black"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      
  - repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    exclude: __init__.py|tests
    args:
    - --max-line-length=110
    - --docstring-convention=google
    - --extend-select=B950
    - --extend-ignore=E203,E501
    additional_dependencies:
    - pep8-naming
    - flake8-bugbear
    - flake8-docstrings
  
  - repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.2.0
  hooks:
  - id: mypy

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint